// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbEEJPmS5KbQ9OZMoGG9KOnm-U7yTLLs',
    appId: '1:209870718696:web:6515de6f82d2a88fcc6b5d',
    messagingSenderId: '209870718696',
    projectId: 'e-commerce-app-5ae25',
    authDomain: 'e-commerce-app-5ae25.firebaseapp.com',
    storageBucket: 'e-commerce-app-5ae25.firebasestorage.app',
    measurementId: 'G-M56VEZPKC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL-dH36zcsda1Jdj-9uERfRL3Z3tcO_I',
    appId: '1:209870718696:android:afdbc3d9166df063cc6b5d',
    messagingSenderId: '209870718696',
    projectId: 'e-commerce-app-5ae25',
    storageBucket: 'e-commerce-app-5ae25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEocvXazgeUgQ68DGeeAKduxxOqIAVoU8',
    appId: '1:209870718696:ios:1ebd746521982655cc6b5d',
    messagingSenderId: '209870718696',
    projectId: 'e-commerce-app-5ae25',
    storageBucket: 'e-commerce-app-5ae25.firebasestorage.app',
    iosBundleId: 'com.example.animationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEocvXazgeUgQ68DGeeAKduxxOqIAVoU8',
    appId: '1:209870718696:ios:1ebd746521982655cc6b5d',
    messagingSenderId: '209870718696',
    projectId: 'e-commerce-app-5ae25',
    storageBucket: 'e-commerce-app-5ae25.firebasestorage.app',
    iosBundleId: 'com.example.animationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbEEJPmS5KbQ9OZMoGG9KOnm-U7yTLLs',
    appId: '1:209870718696:web:549f5550dad4def0cc6b5d',
    messagingSenderId: '209870718696',
    projectId: 'e-commerce-app-5ae25',
    authDomain: 'e-commerce-app-5ae25.firebaseapp.com',
    storageBucket: 'e-commerce-app-5ae25.firebasestorage.app',
    measurementId: 'G-9RYJ316FR0',
  );
}
